#!/usr/bin/env bash
# story: e39s01
# Consumes bigpowers-mcp build_skill_graph MCP tool output (graph.jsonl)
# and emits specs/skill-graph.json + specs/skills-wiki/ OKF concepts.
#
# Supersedes standalone SKILL.md parsing approach (2026-07-04).
# Graph must be built first: run MCP tool `build_skill_graph` or
# `node -e "..."` to generate bigpowers-mcp/graph.jsonl.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GRAPH_IN="$REPO_ROOT/bigpowers-mcp/graph.jsonl"
GRAPH_OUT="$REPO_ROOT/specs/skill-graph.json"
WIKI_DIR="$REPO_ROOT/specs/skills-wiki/skills"

# --help
if [[ "${1:-}" == "--help" ]]; then
  cat <<EOF
Usage: build-skill-graph.sh

Reads bigpowers-mcp/graph.jsonl (generated by e32 build_skill_graph MCP tool)
and produces:
  specs/skill-graph.json  — nodes + typed edges (depends_on, gates, references,
                             enforces, handoff_to)
  specs/skills-wiki/      — one OKF concept markdown file per skill

Options:
  --help    Show this message
  --json    Write only specs/skill-graph.json (skip OKF wiki)
  --wiki    Write only specs/skills-wiki/ (skip JSON graph)

Requires: bigpowers-mcp/graph.jsonl (run build_skill_graph MCP tool first)
EOF
  exit 0
fi

MODE="${1:-both}"
case "$MODE" in
  --json) DO_JSON=1; DO_WIKI=0 ;;
  --wiki) DO_JSON=0; DO_WIKI=1 ;;
  both)   DO_JSON=1; DO_WIKI=1 ;;
  *)      echo "Unknown option: $MODE" >&2; exit 1 ;;
esac

# Pre-flight: graph.jsonl must exist
if [[ ! -f "$GRAPH_IN" ]]; then
  cat >&2 <<EOF
ERROR: $GRAPH_IN not found.

The skill graph has not been built yet. Run the bigpowers-mcp
build_skill_graph tool to generate it:

  # Option A: via MCP inspector
  npx @modelcontextprotocol/inspector node bigpowers-mcp/build/index.js
  # Then call build_skill_graph

  # Option B: via Node.js directly
  node -e "
    const {discoverSkills,readSkillFile}=require('./bigpowers-mcp/build/lib/skill-parser.js');
    const {buildGraphFromSkills}=require('./bigpowers-mcp/build/lib/graph/builder.js');
    const {saveGraph}=require('./bigpowers-mcp/build/lib/graph/store.js');
    const skills=discoverSkills(process.cwd(),()=>'');
    const parsed=skills.map(s=>readSkillFile(process.cwd(),s.name));
    saveGraph('bigpowers-mcp/graph.jsonl', buildGraphFromSkills(parsed));
  "
EOF
  exit 1
fi

# Parse graph.jsonl into nodes + edges
echo "Reading $GRAPH_IN ..." >&2

NODES_JSON="$REPO_ROOT/specs/.tmp-nodes.json"
EDGES_JSON="$REPO_ROOT/specs/.tmp-edges.json"

python3 - "$GRAPH_IN" "$NODES_JSON" "$EDGES_JSON" <<'PYEOF'
import json, sys
from pathlib import Path

graph_in = Path(sys.argv[1])
nodes_out = Path(sys.argv[2])
edges_out = Path(sys.argv[3])

nodes = []
edges = []
entity_count = 0
relation_count = 0
parse_errors = 0

with open(graph_in) as f:
    for lineno, line in enumerate(f, 1):
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as e:
            print(f"WARNING: {graph_in}:{lineno}: invalid JSON — {e}", file=sys.stderr)
            parse_errors += 1
            continue

        if obj.get("type") == "entity":
            nodes.append({
                "name": obj["name"],
                "entityType": obj.get("entityType", "Skill"),
                "observations": obj.get("observations", []),
            })
            entity_count += 1
        elif obj.get("type") == "relation":
            edges.append({
                "from": obj["from"],
                "to": obj["to"],
                "relationType": obj.get("relationType", "unknown"),
            })
            relation_count += 1
        else:
            print(f"WARNING: {graph_in}:{lineno}: unknown type {obj.get('type')}", file=sys.stderr)

with open(nodes_out, "w") as f:
    json.dump(nodes, f, indent=2)
with open(edges_out, "w") as f:
    json.dump(edges, f, indent=2)

print(f"  Entities: {entity_count}, Relations: {relation_count}", file=sys.stderr)
if parse_errors:
    print(f"  Parse errors: {parse_errors}", file=sys.stderr)
PYEOF

# Emit specs/skill-graph.json
if [[ "$DO_JSON" -eq 1 ]]; then
  echo "Writing $GRAPH_OUT ..." >&2
  python3 - "$NODES_JSON" "$EDGES_JSON" "$GRAPH_OUT" <<'PYEOF'
import json, sys

with open(sys.argv[1]) as f:
    nodes = json.load(f)
with open(sys.argv[2]) as f:
    edges = json.load(f)

graph = {"nodes": nodes, "edges": edges}
with open(sys.argv[3], "w") as f:
    json.dump(graph, f, indent=2)

print(f"  nodes: {len(nodes)}, edges: {len(edges)}", file=sys.stderr)
PYEOF
fi

# Emit specs/skills-wiki/ OKF concepts
if [[ "$DO_WIKI" -eq 1 ]]; then
  echo "Writing $WIKI_DIR/ ..." >&2
  rm -rf "$WIKI_DIR"
  mkdir -p "$WIKI_DIR"

  python3 - "$NODES_JSON" "$WIKI_DIR" <<'PYEOF'
import json, sys, re
from pathlib import Path

nodes_file = Path(sys.argv[1])
wiki_dir = Path(sys.argv[2])

with open(nodes_file) as f:
    nodes = json.load(f)

count = 0
for node in nodes:
    name = node["name"]
    observations = node.get("observations", [])

    model = ""
    effort = ""
    description = ""
    for obs in observations:
        if obs.startswith("model: "):
            model = obs[7:]
        elif obs.startswith("effort: "):
            effort = obs[8:]
        elif obs.startswith("description: "):
            description = obs[13:]

    # Derive phase from name convention (simplified)
    phase = "utility"
    critical_path = [
        "survey-context", "elaborate-spec", "model-domain", "define-language",
        "design-interface", "plan-work", "plan-release", "slice-tasks",
        "kickoff-branch", "develop-tdd", "verify-work", "audit-code",
        "commit-message", "release-branch", "security-review",
        "assess-impact", "investigate-bug", "validate-fix",
    ]
    if name in critical_path:
        phase = "critical-path"

    safe_desc = description.replace('"', '\\"')
    md = f"""---
type: Skill
name: {name}
phase: {phase}
model: {model}
effort: {effort}
description: "{safe_desc}"
---

# {name}

**Phase:** {phase}
**Model:** {model}
**Effort:** {effort}

{description}

> Auto-generated by build-skill-graph.sh (e39s01) from bigpowers-mcp/graph.jsonl.
> Source of truth: skills/{name}/SKILL.md
"""
    out_path = wiki_dir / f"{name}.md"
    out_path.write_text(md)
    count += 1

print(f"  concepts written: {count}", file=sys.stderr)
PYEOF
fi

# Cleanup
rm -f "$NODES_JSON" "$EDGES_JSON"

echo "Done." >&2
